### ISSUE TITLE
Adapt code to new version of pint

### ISSUE THREAD

**Issue by saroele** [opengridcc/opengrid#103]
Our build is broken since pint 0.7.  Something must have changed in the pint api between 0.6 and 0.7. Error message:

```
ERROR: test_unit_conversion (test_houseprint_cached.HouseprintTest)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/opengridcc/opengrid/opengrid/library/houseprint/tests/test_houseprint_cached.py", line 253, in test_unit_conversion

    cf = sensor._unit_conversion_factor(diff=True, resample='hour')

  File "/home/travis/build/opengridcc/opengrid/opengrid/library/houseprint/sensor.py", line 143, in _unit_conversion_factor

    source = list(q_int.units)[0] + '/' + resample

TypeError: 'Unit' object is not iterable

```

Thanks to our automated tests :-)

**Comment by saroele** [comment]
fixed
