### ISSUE TITLE
Running default setup instructions generates warnings

### ISSUE THREAD

**Issue by eborghgraef** [opengridcc/opengrid#49]
A clean install following the basic setup instructions with the test script at the end results in the following output:

```
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
./usr/lib/python3.5/importlib/_bootstrap_external.py:423: ImportWarning: Not importing directory /usr/local/lib/python3.5/dist-packages/mpl_toolkits: missing __init__
  _warnings.warn(msg.format(portions[0]), ImportWarning)
.....
----------------------------------------------------------------------
Ran 6 tests in 0.219s

OK
```

System: Linux (Debian Stretch)

**Comment by eborghgraef** [comment]
Commands where as followed:

``` bash
sudo apt install git-all
sudo apt install python3-pip
sudo -H pip3 install -r requirements.txt
sudo apt-get update && sudo apt-get -y install    python3    python3-dev    python3-setuptools    python3-pip    build-essential    libssl-dev    libffi-dev    python3-numpy    python3-scipy    python3-matplotlib    python3-pandas
sudo -H pip3 install jupyter
export PYTHONPATH=$PYTHONPATH:$PWD/opengrid
python3 test_analyses.py
```

**Comment by JrtPec** [comment]
See https://stackoverflow.com/questions/40845304/runtimewarning-numpy-dtype-size-changed-may-indicate-binary-incompatibility

> These warnings are visible whenever you import scipy (or another package) that was compiled against an older numpy than is installed.

The question on Stackoverflow lists a bunch of things you can try to resolve it, including recompiling scipy, but my takeaway is that the warning can safely be ignored ;-)

**Comment by eborghgraef** [comment]
I'll retry this in a clean environment later on, since this is running it on my regular system. Just to figure out if this can be avoided. It's nice to know it can be ignored, but still a bit daunting when getting back into looking at the code. :)

**Comment by eborghgraef** [comment]
Updating to numpy v1.15.1 should get rid of this error. Apparently it was thrown in the past as well, but discarded  but numpy itself before it was shown to the user. While innocent, this bugs me a lot more than it should. 

Upgrading to numpy v1.15.1 throws code related errors though, so this might not be an ideal fix either:

```
======================================================================
ERROR: test_count_peaks (__main__.AnalysisTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "opengrid/tests/test_analyses.py", line 51, in test_count_peaks
    df = datasets.get('gas_dec2016_min')
  File "/home/sahnalys09/Documents/Github/opengrid/opengrid/datasets/datasets.py", line 73, in get
    return sets.unpack(name)
  File "/home/sahnalys09/Documents/Github/opengrid/opengrid/datasets/datasets.py", line 56, in unpack
    df = pd.read_pickle(path, compression='gzip')
TypeError: read_pickle() got an unexpected keyword argument 'compression'

======================================================================
ERROR: test_load_factor (__main__.AnalysisTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "opengrid/tests/test_analyses.py", line 57, in test_load_factor
    ts = og.datasets.get('electricity_2016_hour')
  File "/home/sahnalys09/Documents/Github/opengrid/opengrid/datasets/datasets.py", line 73, in get
    return sets.unpack(name)
  File "/home/sahnalys09/Documents/Github/opengrid/opengrid/datasets/datasets.py", line 56, in unpack
    df = pd.read_pickle(path, compression='gzip')
TypeError: read_pickle() got an unexpected keyword argument 'compression'

======================================================================
ERROR: test_standby (__main__.AnalysisTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "opengrid/tests/test_analyses.py", line 20, in test_standby
    df = datasets.get('elec_power_min_1sensor')
  File "/home/sahnalys09/Documents/Github/opengrid/opengrid/datasets/datasets.py", line 73, in get
    return sets.unpack(name)
  File "/home/sahnalys09/Documents/Github/opengrid/opengrid/datasets/datasets.py", line 56, in unpack
    df = pd.read_pickle(path, compression='gzip')
TypeError: read_pickle() got an unexpected keyword argument 'compression'

======================================================================
ERROR: test_standby_with_time_window (__main__.AnalysisTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "opengrid/tests/test_analyses.py", line 27, in test_standby_with_time_window
    df = datasets.get('elec_power_min_1sensor')
  File "/home/sahnalys09/Documents/Github/opengrid/opengrid/datasets/datasets.py", line 73, in get
    return sets.unpack(name)
  File "/home/sahnalys09/Documents/Github/opengrid/opengrid/datasets/datasets.py", line 56, in unpack
    df = pd.read_pickle(path, compression='gzip')
TypeError: read_pickle() got an unexpected keyword argument 'compression'

----------------------------------------------------------------------
Ran 6 tests in 0.007s

FAILED (errors=4)
```

**Comment by JrtPec** [comment]
What version of Pandas are you running? The `compression` keyword for `read_pickle` was introduced in version 0.20.0.

**Comment by eborghgraef** [comment]
Upgrading numpy to v1.15.1 and pandas to v0.23.4 seems to fix everything.

Was running on v1.12.1 and v0.19.2 before

```
python3 opengrid/tests/test_analyses.py 
......
----------------------------------------------------------------------
Ran 6 tests in 0.174s

OK
```

It's strange that these packages aren't updated to the newest versions on install.

Perhaps it's a good idea to specify the current version numbers in the requirements.txt to avoid sudden build failures and update them after checking locally? @JrtPec

**Comment by EpoxyD** [comment]
```
python3 opengrid/tests/test_analyses.py 
......
----------------------------------------------------------------------
Ran 6 tests in 0.174s

OK

```
